### ISSUE TITLE
Perform `overflow` check outside of `merkle_prove_layer` 

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#56]
As of now, the overflow chip gets initiated, loaded and assigned inside `merkle_prove_layer` 

https://github.com/summa-dev/summa-solvency/blob/ad3ce074b12a2943cecef145255baa0bd887f05b/zk_prover/src/chips/merkle_sum_tree.rs#L372-L390

This approach is inefficient because it requires the chip to be loaded at every merkle_prove_layer, generating a 8 bits fixed column at every level, which is not necessary. 

Furthermore, I suggest performing the overflow check also on the `leaf_balances` which is not performed now

**Comment by ameya-deshmukh** [comment]
@enricobottazzi can I take this up?

**Comment by enricobottazzi** [comment]
Absolutely! I suggest you to branch out from `feat-53`

**Comment by sifnoc** [comment]
I am not certain whether this approach is more efficient. One method could be to check for overflow in the balances, namely `leaf_balance` and `path_of_element_balances`, before assigning the values to `MerkleSumTreeChip`.

**Comment by enricobottazzi** [comment]
This approach has been applied to #67 by loading the overflow chip inside `syntesize` rather than having to load it at every merkle sum tree level as it was happening before. That was the efficiency measure that I was referring to. 

What do you mean to check overflow before the values get assigned?

**Comment by sifnoc** [comment]
Currently, we are checking for overflow in the values evaluated by the `assign_nodes_balance_per_asset` method in `MerkleSumTreeChip`. 

https://github.com/summa-dev/summa-solvency/blob/eee534af6311d89b9c91c36d27f1542bbffa5909/zk_prover/src/circuits/merkle_sum_tree.rs#L185-L186

How about we check for overflow before evaluating `assign_nodes_balance_per_asset`? 

This would require modifying both the `OverflowChip` and `MerkleSumTreeChip` so that the `MerkleSumTreeChip` can utilize the cells that have already undergone overflow checks for `leaf_balances` and `path_element_balances`

We could then use the modified chips like this:

```Rust
let checked_overflow_balance = overflow_check_chip.assign(leaf_balance)

merkle_sum_tree_chip.assign_nodes_balance_per_asset(
						// ...
                        &checked_overflow_balance[asset],
                        checked_overflow_element_balance[level][asset],
                        swap_bit_level.clone(),
)
```
This would allow us to use `checked_overflow_balance` in `assign_nodes_balance_per_asset`.

I'm not sure how this would affect performance, it's just something I thought might be worth considering.

**Comment by enricobottazzi** [comment]
@sifnoc yeah I see your point! I see that it could be beneficial for failing proof that will fail before having to perform the hashing. Do you see any other benefit regarding proving time? Maybe it's still worth trying after #75 gets merged so we can compare the two different approaches
